module.exports = {
  Potrace: {
    TURNPOLICY_BLACK: 'TURNPOLICY_BLACK',
    TURNPOLICY_WHITE: 'TURNPOLICY_WHITE',
    TURNPOLICY_LEFT: 'TURNPOLICY_LEFT',
    TURNPOLICY_RIGHT: 'TURNPOLICY_RIGHT',
    TURNPOLICY_MINORITY: 'TURNPOLICY_MINORITY',
    TURNPOLICY_MAJORITY: 'TURNPOLICY_MAJORITY',
  },
};

